name: camt_terminator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.40
  audio_session: ^0.1.19
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/knife.png
    - assets/images/medkit.png
    - assets/images/shield.png
    - assets/images/shotgun.png
    - assets/images/card1.png
    - assets/images/card2.png
    - assets/images/card3.png
    - assets/images/cardEmpty.png
    - assets/images/deck.png
    - assets/images/player.png
    - assets/images/boss1.png
    - assets/images/boss2.png
    - assets/images/boss3.png
    - assets/images/boss4.png
    - assets/images/combat_background.png

    - assets/song/Con_theme.mp3
    - assets/song/Party_theme.mp3
    - assets/song/Plub_theme.mp3
    - assets/song/Tew_theme.mp3
